version: '3.7'

services:

  apache:
    container_name: ${APACHE_NAME}
    build:
      context: .
      args:
        ENV: ${ENV}
        APACHE_TAG: ${APACHE_TAG}
    restart: always
    networks:
      - default
    ports:
      - ${APACHE_HTTP_PORT}:8080
      - ${APACHE_HTTPS_PORT}:8443
    environment:
      ENV: ${ENV}
